# Generated by Django 2.1.7 on 2019-03-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acerca_de_mi',
            field=models.CharField(default='.....', max_length=1000, verbose_name='Acerca de mi'),
        ),
        migrations.AddField(
            model_name='user',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AddField(
            model_name='user',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Telefono'),
        ),
    ]
