# Generated by Django 2.1.7 on 2019-03-05 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('aula_creacion', models.DateTimeField(auto_now_add=True)),
                ('aula_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_contenido', models.TextField(verbose_name='Contenido')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('doc_archivo', models.FileField(upload_to='documentos_meteria/', verbose_name='archivo')),
                ('doc_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('materia_id', models.AutoField(primary_key=True, serialize=False)),
                ('materia_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('materia_creado', models.DateTimeField(auto_now_add=True)),
                ('materia_archivos', models.ManyToManyField(to='ctr_escolar.Documento', verbose_name='Archivos')),
                ('materia_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Aula', verbose_name='Aula')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tarea_descripcion', models.CharField(max_length=50, verbose_name='Descripcion')),
                ('tarea_fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('tarea_fecha_termino', models.DateField(verbose_name='Fecha de Final')),
                ('tarea_tipo', models.CharField(choices=[('ENTREGA', 'ENTREGA'), ('PARA CALIFICAR', 'PARA CALIFICAR')], max_length=8, verbose_name='Tipo de tarea')),
            ],
        ),
        migrations.CreateModel(
            name='TareaDocumento',
            fields=[
                ('tareaDocumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tareaDocumento_archivo', models.FileField(upload_to='documentos_tareas/', verbose_name='Archivo')),
                ('tareaDocumento_comentario_alumno', models.CharField(max_length=500, verbose_name='Comentario Alumno')),
                ('tareaDocumento_comentario_maestro', models.CharField(max_length=500, verbose_name='Comentario Maestro')),
                ('tareaDocumento_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('tareaDocumento_status', models.BooleanField(verbose_name='Status Tarea')),
                ('tareaDocumento_calificacion', models.FloatField(verbose_name='Calificación')),
                ('tareaDocumento_tipo', models.IntegerField(choices=[(1, 'Google Drive'), (2, 'Propio Sistema')], verbose_name='Tipo documento')),
                ('tareaDocumento_Tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Tarea', verbose_name='Tarea')),
                ('tareaDocumento_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pertenece a')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('unidad_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Materia', verbose_name='Materia')),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Unidad', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Materia', verbose_name='Materia'),
        ),
    ]
