# Generated by Django 2.2 on 2019-08-11 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aula_nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('aula_creacion', models.DateTimeField(auto_now_add=True)),
                ('aula_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.AutoField(primary_key=True, serialize=False)),
                ('blog_titulo', models.CharField(max_length=250, verbose_name='Titulo')),
                ('blog_descripcion', models.CharField(max_length=500, verbose_name='Descripcion')),
                ('blog_contenido', models.TextField(blank=True, null=True, verbose_name='Contenido')),
                ('blog_imagen', models.ImageField(upload_to='img_blogs/', verbose_name='Imagen Blog')),
                ('blog_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('blog_ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('doc_id', models.AutoField(primary_key=True, serialize=False)),
                ('doc_nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('doc_archivo', models.FileField(upload_to='documentos_meteria/', verbose_name='archivo')),
                ('doc_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('materia_id', models.AutoField(primary_key=True, serialize=False)),
                ('materia_nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('materia_creado', models.DateTimeField(auto_now_add=True)),
                ('materia_archivos', models.ManyToManyField(to='ctr_escolar.Documento', verbose_name='Archivos')),
                ('materia_aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Aula', verbose_name='Aula')),
                ('materia_registro_alumnnos', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Registro_materia')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('unidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('unidad_nombre', models.CharField(max_length=500, verbose_name='Nombre')),
                ('unidad_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Materia', verbose_name='Materia')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('tarea_id', models.AutoField(primary_key=True, serialize=False)),
                ('tarea_nombre', models.CharField(max_length=400, verbose_name='Nombre')),
                ('tarea_descripcion', models.CharField(max_length=800, verbose_name='Descripcion')),
                ('tarea_fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('tarea_fecha_termino', models.DateField(verbose_name='Fecha de Final')),
                ('tarea_tipo', models.CharField(choices=[('ENTREGA', 'ENTREGA'), ('PARA CALIFICAR', 'PARA CALIFICAR')], max_length=20, verbose_name='Tipo de tarea')),
                ('tarea_unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Unidad', verbose_name='Unidad')),
            ],
        ),
        migrations.CreateModel(
            name='ComentarioBlog',
            fields=[
                ('comentario_blogID', models.AutoField(primary_key=True, serialize=False)),
                ('comentario_comentario', models.TextField(verbose_name='Deje aqui su comentario')),
                ('comentario_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('comentario_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Blog', verbose_name='ID Blog')),
                ('comentario_comentado_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comentado por')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionUnidad',
            fields=[
                ('calU_id', models.AutoField(primary_key=True, serialize=False)),
                ('calU_Materia_nombre', models.CharField(max_length=500, verbose_name='Materia')),
                ('calU_unidadNombre', models.CharField(max_length=600, verbose_name='Unidad')),
                ('calU_unidadID', models.IntegerField(verbose_name='Unidad id')),
                ('calU_materiaID', models.IntegerField(verbose_name='Materia id')),
                ('calU_calificacion', models.FloatField()),
                ('calU_entrego', models.CharField(max_length=50, verbose_name='Entrego')),
                ('calU_falta_calificar', models.CharField(default='no', max_length=50, verbose_name='Falta Calificar')),
                ('calU_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionMateria',
            fields=[
                ('calM_id', models.AutoField(primary_key=True, serialize=False)),
                ('calM_nombre_materia', models.CharField(max_length=400, verbose_name='Materia Nombre')),
                ('calM_materiaID', models.CharField(max_length=400, verbose_name='Materia Nombre')),
                ('calM_calificacionFinal', models.FloatField(verbose_name='Calificación')),
                ('calM_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='alumno')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_materia',
            field=models.ManyToManyField(to='ctr_escolar.Materia', verbose_name='Relacionar'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TareaDocumento',
            fields=[
                ('tareaDocumento_id', models.AutoField(primary_key=True, serialize=False)),
                ('tareaDocumento_archivo', models.FileField(upload_to='documentos_tareas/', verbose_name='Archivo')),
                ('tareaDocumento_comentario_alumno', models.CharField(max_length=500, verbose_name='Comentario Alumno')),
                ('tareaDocumento_comentario_maestro', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentario Maestro')),
                ('tareaDocumento_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('tareaDocumento_status', models.BooleanField(default=False, verbose_name='Status Tarea')),
                ('tareaDocumento_calificacion', models.FloatField(blank=True, null=True, verbose_name='Calificación')),
                ('tareaDocumento_actualizado', models.DateTimeField(auto_now=True)),
                ('tareaDocumento_Tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Tarea', verbose_name='Tarea')),
                ('tareaDocumento_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pertenece a')),
            ],
            options={
                'ordering': ['-tareaDocumento_actualizado'],
                'unique_together': {('tareaDocumento_pertenece', 'tareaDocumento_Tarea')},
            },
        ),
    ]
