# Generated by Django 2.2 on 2019-08-11 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ctr_escolar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tareadocumento',
            name='tareaDocumento_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Pertenece a'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tarea_unidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Unidad', verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='materia',
            name='materia_archivos',
            field=models.ManyToManyField(to='ctr_escolar.Documento', verbose_name='Archivos'),
        ),
        migrations.AddField(
            model_name='materia',
            name='materia_aula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Aula', verbose_name='Aula'),
        ),
        migrations.AddField(
            model_name='materia',
            name='materia_registro_alumnnos',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Registro_materia'),
        ),
        migrations.AddField(
            model_name='documento',
            name='doc_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comentarioblog',
            name='comentario_blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Blog', verbose_name='ID Blog'),
        ),
        migrations.AddField(
            model_name='comentarioblog',
            name='comentario_comentado_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comentado por'),
        ),
        migrations.AddField(
            model_name='calificacionunidad',
            name='calU_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='calificacionmateria',
            name='calM_alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='alumno'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_materia',
            field=models.ManyToManyField(to='ctr_escolar.Materia', verbose_name='Relacionar'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aula',
            name='aula_pertenece',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tareadocumento',
            unique_together={('tareaDocumento_pertenece', 'tareaDocumento_Tarea')},
        ),
    ]
