# Generated by Django 2.1.7 on 2019-03-07 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctr_escolar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_creado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creado en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_descripcion',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='Descripcion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img_blogs/', verbose_name='Imagen Blog'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_pertenece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Titulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion'),
        ),
    ]
