# Generated by Django 2.1.7 on 2019-03-07 22:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctr_escolar', '0002_auto_20190307_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='Regitro_materia',
            fields=[
                ('regis_id', models.AutoField(primary_key=True, serialize=False)),
                ('regis_calificacion_final', models.FloatField(blank=True, null=True, verbose_name='Calificacion')),
                ('regis_fecha_inscrito', models.DateTimeField(auto_now_add=True, verbose_name='Inscrito')),
                ('regis_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('regis_materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Materia', verbose_name='Alumno a la materia de')),
            ],
        ),
    ]
