# Generated by Django 2.2 on 2019-08-12 01:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0002_auto_20190811_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='tarea_porcentaje',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Valor en %'),
        ),
    ]
