# Generated by Django 2.1.7 on 2019-03-08 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctr_escolar', '0004_auto_20190308_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='materia_registro_alumnnos',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Registro_materia'),
        ),
    ]
