# Generated by Django 2.1.7 on 2019-03-08 20:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctr_escolar', '0005_materia_materia_registro_alumnnos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_titulo',
            field=models.CharField(max_length=250, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='doc_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='materia_nombre',
            field=models.CharField(max_length=150, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_descripcion',
            field=models.CharField(max_length=800, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='tarea',
            name='tarea_nombre',
            field=models.CharField(max_length=400, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='unidad',
            name='unidad_nombre',
            field=models.CharField(max_length=500, verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='tareadocumento',
            unique_together={('tareaDocumento_pertenece', 'tareaDocumento_Tarea')},
        ),
    ]
