# Generated by Django 2.1.7 on 2019-03-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0006_auto_20190308_1458'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareadocumento',
            name='tareaDocumento_tipo',
        ),
        migrations.AlterField(
            model_name='tareadocumento',
            name='tareaDocumento_calificacion',
            field=models.FloatField(blank=True, null=True, verbose_name='Calificación'),
        ),
        migrations.AlterField(
            model_name='tareadocumento',
            name='tareaDocumento_comentario_maestro',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentario Maestro'),
        ),
        migrations.AlterField(
            model_name='tareadocumento',
            name='tareaDocumento_status',
            field=models.BooleanField(default=False, verbose_name='Status Tarea'),
        ),
    ]
