# Generated by Django 2.1.7 on 2019-03-09 20:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0007_auto_20190308_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareadocumento',
            options={'ordering': ['-tareaDocumento_actualizado']},
        ),
        migrations.AddField(
            model_name='tareadocumento',
            name='tareaDocumento_actualizado',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
