# Generated by Django 2.1.7 on 2019-03-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0008_auto_20190309_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tareadocumento',
            options={'ordering': ['tareaDocumento_actualizado']},
        ),
        migrations.AlterField(
            model_name='tareadocumento',
            name='tareaDocumento_actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
