# Generated by Django 2.1.7 on 2019-03-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0009_auto_20190309_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='tarea_tipo',
            field=models.CharField(choices=[('ENTREGA', 'ENTREGA'), ('PARA CALIFICAR', 'PARA CALIFICAR')], max_length=20, verbose_name='Tipo de tarea'),
        ),
    ]
