# Generated by Django 2.1.7 on 2019-03-11 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctr_escolar', '0010_auto_20190309_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionUnidad',
            fields=[
                ('calU_id', models.AutoField(primary_key=True, serialize=False)),
                ('calU_Materia_nombre', models.CharField(max_length=500, verbose_name='Materia')),
                ('calU_unidadNombre', models.CharField(max_length=600, verbose_name='Unidad')),
                ('calU_unidadID', models.IntegerField(verbose_name='Unidad id')),
                ('calU_materiaID', models.IntegerField(verbose_name='Materia id')),
                ('calU_calificacion', models.FloatField()),
                ('calU_entrego', models.IntegerField(verbose_name='Entrego')),
                ('calU_pertenece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.AlterModelOptions(
            name='tareadocumento',
            options={'ordering': ['-tareaDocumento_actualizado']},
        ),
    ]
