# Generated by Django 2.1.7 on 2019-03-11 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0011_auto_20190311_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionunidad',
            name='calU_entrego',
            field=models.CharField(max_length=50, verbose_name='Entrego'),
        ),
    ]
