# Generated by Django 2.1.7 on 2019-03-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0012_auto_20190311_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionunidad',
            name='calU_falta_calificar',
            field=models.CharField(default='no', max_length=50, verbose_name='Falta Calificar'),
        ),
    ]
