# Generated by Django 2.1.7 on 2019-03-11 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctr_escolar', '0013_calificacionunidad_calu_falta_calificar'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionMateria',
            fields=[
                ('calM_id', models.AutoField(primary_key=True, serialize=False)),
                ('calM_nombre_materia', models.CharField(max_length=400, verbose_name='Materia Nombre')),
                ('calM_materiaID', models.CharField(max_length=400, verbose_name='Materia Nombre')),
                ('calM_calificacionFinal', models.FloatField(verbose_name='Calificación')),
                ('calM_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='alumno')),
            ],
        ),
    ]
