# Generated by Django 2.1.7 on 2019-03-11 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ctr_escolar', '0014_calificacionmateria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioBlog',
            fields=[
                ('comentario_blogID', models.AutoField(primary_key=True, serialize=False)),
                ('comentario_comentario', models.TextField(verbose_name='Contenido')),
                ('comentario_creado', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('comentario_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctr_escolar.Blog', verbose_name='ID Blog')),
                ('comentario_comentado_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Comentado por')),
            ],
        ),
    ]
