# Generated by Django 2.1.7 on 2019-03-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0015_comentarioblog'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='regitro_materia',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='regitro_materia',
            name='regis_alumno',
        ),
        migrations.RemoveField(
            model_name='regitro_materia',
            name='regis_materia',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_materia',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_materia',
            field=models.ManyToManyField(to='ctr_escolar.Materia', verbose_name='Relacionar'),
        ),
        migrations.AlterField(
            model_name='comentarioblog',
            name='comentario_comentario',
            field=models.TextField(verbose_name='Deje aqui su comentario'),
        ),
        migrations.DeleteModel(
            name='Regitro_materia',
        ),
    ]
