# Generated by Django 2.1.7 on 2019-03-29 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0016_auto_20190321_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_contenido',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
