# Generated by Django 2.2 on 2019-06-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctr_escolar', '0018_auto_20190612_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='materia_archivos',
            field=models.ManyToManyField(to='ctr_escolar.Documento', verbose_name='Archivos'),
        ),
    ]
