# Generated by Django 2.1.7 on 2019-04-05 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='mensaje_status',
            field=models.IntegerField(choices=[(1, 'Entregado'), (2, 'Visto')], default=1, verbose_name='Estado'),
        ),
    ]
